version: '3.8'
services: 
  mongo:
    image: mongo:8.0.4
    container_name: mean-db
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongo-data: